---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings

title: Homepage

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey

background:
  image: http://192.168.66.18:3111/random-image
  #blur: sm # sm, "", md, xl... see https://tailwindcss.com/docs/backdrop-blur
  saturate: 75 # 0, 50, 100... see https://tailwindcss.com/docs/backdrop-saturate
  brightness: 75 # 0, 50, 75... see https://tailwindcss.com/docs/backdrop-brightness
  opacity: 45 # 0-100